version: '{build}'
image: Visual Studio 2017
skip_tags: true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
environment:
  COVERALLS_REPO_TOKEN:
    secure: 7ZrzjrrwL6JAHiT8h5KsUbT4kXdLYLDtc
build_script:
  - dotnet build -c Release
