name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core 2.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1

    - name: Setup .NET Core 3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1

    - name: Setup side by side .NET SDKs on Windows
      shell: pwsh
      run: |
          $version = Split-Path (Split-Path $ENV:DOTNET_ROOT -Parent) -Leaf;
          echo "Version is: ${version}.";
          $root = Split-Path (Split-Path $ENV:DOTNET_ROOT -Parent) -Parent;
          echo "Root is: ${root}.";
          $directories = Get-ChildItem $root | Where-Object { $_.Name -ne $version };

          foreach ($dir in $directories)
          {
              $from = $dir.FullName;
              $to = "$root\$version";
              echo "Copying from ${from} to ${to}.";
              Copy-Item "$from\*" $to -Recurse -Force;
          }

    - name: Check dotnet sdk install
      run: dotnet --info

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Test
      run: dotnet test -c Release --no-restore --no-build --verbosity normal
    
    - name: Publish Casbin.Net
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: NetCasbin/NetCasbin.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          NUGET_SOURCE: https://api.nuget.org
