name: Benchmark

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  benchmark:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core 2.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1

    - name: Setup .NET Core 3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1

    - name: Check dotnet sdk install
      run: dotnet --info

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Test
      run: dotnet test -c Release --no-restore --no-build --verbosity normal

    - name: Run Benchmark
      run: |
        cd Casbin.Benchmark
        dotnet run -c Release -f netcoreapp31 --filter **

    - name: Upload benchmark results to artefacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: "drop-ci-benchmark-resuls"
        path: './Casbin.Benchmark/BenchmarkDotNet.Artifacts'
